//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinHW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinHW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string BtnProp1 {
            get {
                return ResourceManager.GetString("BtnProp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string BtnProp1_2 {
            get {
                return ResourceManager.GetString("BtnProp1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp.
        /// </summary>
        internal static string BtnProp2 {
            get {
                return ResourceManager.GetString("BtnProp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp.
        /// </summary>
        internal static string BtnProp2_2 {
            get {
                return ResourceManager.GetString("BtnProp2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 min.
        /// </summary>
        internal static string BtnProp3 {
            get {
                return ResourceManager.GetString("BtnProp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 min.
        /// </summary>
        internal static string BtnProp3_2 {
            get {
                return ResourceManager.GetString("BtnProp3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string BtnProp4 {
            get {
                return ResourceManager.GetString("BtnProp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string BtnProp4_2 {
            get {
                return ResourceManager.GetString("BtnProp4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big.
        /// </summary>
        internal static string BtnProp4_3 {
            get {
                return ResourceManager.GetString("BtnProp4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your order.
        /// </summary>
        internal static string ButtonString1 {
            get {
                return ResourceManager.GetString("ButtonString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        internal static string ButtonString2 {
            get {
                return ResourceManager.GetString("ButtonString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        internal static string LabelProp1 {
            get {
                return ResourceManager.GetString("LabelProp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acidity.
        /// </summary>
        internal static string LabelProp2 {
            get {
                return ResourceManager.GetString("LabelProp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        internal static string LabelProp3 {
            get {
                return ResourceManager.GetString("LabelProp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string LabelProp4 {
            get {
                return ResourceManager.GetString("LabelProp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By UXDivers.
        /// </summary>
        internal static string LblCoffeMaker1 {
            get {
                return ResourceManager.GetString("LblCoffeMaker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jungle Expresso.
        /// </summary>
        internal static string LblCoffeName1 {
            get {
                return ResourceManager.GetString("LblCoffeName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 2.75.
        /// </summary>
        internal static string LblCoffePrice1 {
            get {
                return ResourceManager.GetString("LblCoffePrice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 3.50.
        /// </summary>
        internal static string LblCoffePrice2 {
            get {
                return ResourceManager.GetString("LblCoffePrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 4.00.
        /// </summary>
        internal static string LblCoffePrice3 {
            get {
                return ResourceManager.GetString("LblCoffePrice3", resourceCulture);
            }
        }
    }
}
